# ===================================================================
# Spring Boot configuration for the "prod" profile.
# ===================================================================

logging:
  level:
    ROOT: INFO
    tech.jhipster: INFO
    mailmerge: INFO

management:
  prometheus:
    metrics:
      export:
        enabled: false

spring:
  security:
    oauth2:
      client:
        registration:
          azure:
            provider: azure
            client-id: ${AZURE_CLIENT_ID}
            client-secret: ${AZURE_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "https://mailmerge.bham.team/login/oauth2/code/azure"
            scope:
              - openid
              - profile
              - email
              - offline_access
              - Mail.Send

          oidc:
            provider: azure
            client-id: ${AZURE_CLIENT_ID}
            client-secret: ${AZURE_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "https://mailmerge.bham.team/login/oauth2/code/azure"
            scope:
              - openid
              - profile
              - email
              - offline_access
              - Mail.Send

        provider:
          azure:
            authorization-uri: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
            token-uri: https://login.microsoftonline.com/common/oauth2/v2.0/token
            jwk-set-uri: https://login.microsoftonline.com/common/discovery/v2.0/keys
            user-info-uri: https://graph.microsoft.com/oidc/userinfo
            user-name-attribute: sub

          oidc:
            issuer-uri: https://login.microsoftonline.com/organizations/v2.0

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://mailmerge-postgresql:5432/mailmerge
    username: mailmerge
    password:
    hikari:
      poolName: Hikari
      auto-commit: false

  liquibase:
    contexts: prod

  thymeleaf:
    cache: true

server:
  port: 8080
  shutdown: graceful
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,application/javascript,application/json,image/svg+xml
    min-response-size: 1024
  forward-headers-strategy: native

jhipster:
  http:
    cache:
      timeToLiveInDays: 1461
  cache:
    ehcache:
      time-to-live-seconds: 3600
      max-entries: 1000
  logging:
    use-json-format: false
    logstash:
      enabled: false
      host: localhost
      port: 5000
      ring-buffer-size: 512
  cors:
    allowed-origins: 'https://mailmerge.bham.team,https://www.mailmerge.bham.team'
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: 'Authorization,Link,X-Total-Count'
    allow-credentials: true
    max-age: 1800
