package mailmerge.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class HeadingAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHeadingAllPropertiesEquals(Heading expected, Heading actual) {
        assertHeadingAutoGeneratedPropertiesEquals(expected, actual);
        assertHeadingAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHeadingAllUpdatablePropertiesEquals(Heading expected, Heading actual) {
        assertHeadingUpdatableFieldsEquals(expected, actual);
        assertHeadingUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHeadingAutoGeneratedPropertiesEquals(Heading expected, Heading actual) {
        assertThat(expected)
            .as("Verify Heading auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHeadingUpdatableFieldsEquals(Heading expected, Heading actual) {
        assertThat(expected)
            .as("Verify Heading relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertHeadingUpdatableRelationshipsEquals(Heading expected, Heading actual) {
        assertThat(expected)
            .as("Verify Heading relationships")
            .satisfies(e -> assertThat(e.getProject()).as("check project").isEqualTo(actual.getProject()));
    }
}
