name: build and deploy jhipster application
on: [push, pull_request]
jobs:
  publish-docker:
    name: Publish Docker
    if: contains(github.ref, 'refs/heads/main') || startsWith(github.ref, 'refs/tags/')
    concurrency:
      group: deployment
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    services:
      docker:
        image: docker:dind
        options: >-
          --privileged
          --env DOCKER_TLS_CERTDIR=
        ports:
          - 2375:2375
    env:
      DOCKER_HOST: 'tcp://127.0.0.1:2375'
      DOCKER_DRIVER: overlay2
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Wait for Docker Daemon
        run: |
          for i in {1..10}; do
            if docker info; then
              break
            fi
            echo "Waiting for Docker Daemon..."
            sleep 3
          done

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-v1-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-v1-

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: node_modules-

      - name: Build and push Docker image to ghcr
        run: |
          set -e
          OWNER_LC="$(printf '%s' "${GITHUB_REPOSITORY_OWNER}" | tr '[:upper:]' '[:lower:]')"
          REPO_LC="$(printf '%s' "${GITHUB_REPOSITORY##*/}" | tr '[:upper:]' '[:lower:]')"

          if [ -z "$OWNER_LC" ] || [ -z "$REPO_LC" ]; then
            echo "ERROR: OWNER_LC='${OWNER_LC}' REPO_LC='${REPO_LC}'"
            exit 1
          fi

          echo "pushing ghcr.io/${OWNER_LC}/${REPO_LC}:${GITHUB_SHA}"
          ./mvnw -ntp clean compile jib:build -DskipTests -Pprod \
            -Djib.to.auth.username="${GITHUB_ACTOR}" \
            -Djib.to.auth.password="${{ secrets.GITHUB_TOKEN }}" \
            -Djib.to.image="ghcr.io/${OWNER_LC}/${REPO_LC}" \
            -Djib.to.tags="latest,${GITHUB_SHA}" \
            -Dmaven.repo.local="$MAVEN_USER_HOME"
        env:
          MAVEN_USER_HOME: ~/.m2/repository

  deploy-dev:
    name: deploy development app via ssh
    runs-on: self-hosted
    needs: publish-docker
    if: success() && ( contains(github.ref, 'refs/heads/main') || startsWith(github.ref, 'refs/tags/') )
    concurrency:
      group: deployment

    env:
      RSA_PRIVATE_KEY: ${{secrets.RSA_PRIVATE_KEY}}
      URL: '${{ github.event.repository.name }}.bham.team'
      DEVURL: '${{ github.event.repository.name }}.dev.bham.team'
      ACME: 'https://acme-v02.api.letsencrypt.org/directory'
      ACME_STAGING: 'https://acme-staging-v02.api.letsencrypt.org/directory'
      CI_REGISTRY_USER: ${{ github.actor }}
      CI_REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      CI_REGISTRY: ghcr.io

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$RSA_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa

      - name: Add SSH known hosts
        run: |
          ssh-keyscan -H ${{ secrets.DEPLOY_IP }} >> ~/.ssh/known_hosts

      - name: Save CI variables for transfer
        run: |
          set -e
          OWNER_LC="$(printf '%s' "${GITHUB_REPOSITORY_OWNER}" | tr '[:upper:]' '[:lower:]')"
          REPO_LC="$(printf '%s' "${GITHUB_REPOSITORY##*/}" | tr '[:upper:]' '[:lower:]')"

          if [ -z "$OWNER_LC" ] || [ -z "$REPO_LC" ]; then
            echo "ERROR: OWNER_LC='${OWNER_LC}' REPO_LC='${REPO_LC}'"
            exit 1
          fi

          printf "CI_REGISTRY_USER=%s\nCI_REGISTRY_PASSWORD=%s\nCI_REGISTRY_IMAGE=%s\nCI_COMMIT_TAG=%s\nCI_REGISTRY=%s\nACME=%s\nDEVURL=%s\nURL=%s\nDEPLOY_IP=%s\nEMAIL=%s\nAZURE_CLIENT_ID=%s\nAZURE_CLIENT_SECRET=%s\nAZURE_TENANT_ID=%s\n" \
            "${{ env.CI_REGISTRY_USER }}" \
            "${{ env.CI_REGISTRY_PASSWORD }}" \
            "ghcr.io/${OWNER_LC}/${REPO_LC}" \
            "${{ github.sha }}" \
            "${{ env.CI_REGISTRY }}" \
            "${{ env.ACME_STAGING }}" \
            "${{ env.DEVURL }}" \
            "${{ env.URL }}" \
            "${{ secrets.DEPLOY_IP }}" \
            "${{ github.event.head_commit.author.email }}" \
            "${{ secrets.AZURE_CLIENT_ID }}" \
            "${{ secrets.AZURE_CLIENT_SECRET }}" \
            "${{ secrets.AZURE_TENANT_ID }}" \
            > src/main/docker/.env

      - name: Install Docker and prepare the server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_IP }} "
            rm -rf ~/team-project || true
            which docker || sh team-project/install-docker.sh
          "

      - name: Transfer files to the server
        run: |
          scp -o StrictHostKeyChecking=no -r src/main/docker/ ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_IP }}:~/team-project

      - name: Install app on the server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_IP }} "sh team-project/install-app.sh"

      - name: Deploy and clean Docker
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_IP }} "
            docker compose --env-file ~/team-project/.env -f ~/team-project/dev.yml up -d
            docker system prune --force --filter 'until=24h'
          "

  deploy-prod:
    name: deploy production version via ssh
    runs-on: self-hosted
    needs: deploy-dev
    if: success() && startsWith(github.ref, 'refs/tags/')
    concurrency:
      group: deployment

    env:
      RSA_PRIVATE_KEY: ${{secrets.RSA_PRIVATE_KEY}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$RSA_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa

      - name: Add SSH known hosts
        run: |
          ssh-keyscan -H ${{ secrets.DEPLOY_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to production
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_IP }} "
            docker compose --env-file ~/team-project/.env -f ~/team-project/prd.yml up -d
            docker system prune --force --filter 'until=24h'
          "
